### ISSUE TITLE
Own word: if you use an underscore in the word, you get caught in the program

### ISSUE THREAD

**Issue by ewolf34** [9Lukas5/Hangman#8]

**Comment by 9Lukas5** [comment]
@ewolf34 this is only the case if the word has ONLY non-letter character(s), right?

**Comment by ewolf34** [comment]
Yes

**Comment by 9Lukas5** [comment]
Alright, that should be fine now, too: 38e813c9d1dbcc7c7e1558a40b41a7ed56f161b6

Side-effect of this change is that you get a congratulations message if you guessed the word in single letters, too.

**Comment by 9Lukas5** [comment]
Damn, we have to avoid starting the in-game if the word itself contains ANY underscore -.-
